---
booktitle: Proceedings of the NeurIPS 2019 Competition and Demonstration Track
shortname: NeurIPSCDT
volume: 123
year: '2020'
start: 2019-12-08
end: 2019-12-14
published: 2020-08-19
url: https://proceedings.mlr.press
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: NeurIPSCDT-2019
month: 0
cycles: false
bibtex_editor: Escalante, Hugo Jair and Hadsell, Raia
editor:
- given: Hugo Jair
  family: Escalante
- given: Raia
  family: Hadsell
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the NeurIPS 2019 Competition and Demonstration Track
    Held in Vancouver, CA on 08-14 December 2019

  Published as Volume 123 by the Proceedings of Machine Learning Research on 19 August 2020.

  Volume Edited by:
    Hugo Jair Escalante
    Raia Hadsell

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: '08--14 Dec'
author:
  name: PMLR
baseurl: "/v123"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v123
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: NeurIPS 2019 Competition and Demonstration Track
  url: 
  location: Vancouver, CA
  dates:
  - 2019-12-08
  - 2019-12-09
  - 2019-12-10
  - 2019-12-11
  - 2019-12-12
  - 2019-12-13
  - 2019-12-14
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v123/NeurIPSCDT-2019.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v123/NeurIPSCDT-2019.bib
